version: "2"
services:
    mongo:
        image: mongo
        ports:
            - 27017:27017
    web:
        build: .
        command: npm run seed
        command: npm run start
        volumes:
            - ./:/app
        ports:
            - "3000:3000"
        links:
            - mongo
